swagger: '2.0'

info:
  title: User API
  version: "0.1.0"

paths:
  /users/{username}:
    get:
      x-swagger-router-controller: gm_analytics
      operationId: handlers.get_user_info
      summary: Returns user information.
      parameters:
        - name: username
          in: path
          required: true
          type: string
          format: path
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              user_info:
                type: string
                description: User information
